### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by carl-amit** [ryersondmp/sa11y#72]
## Error Description
```javascript
TypeError: Cannot read properties of null (reading 'querySelectorAll')
    at https://cdn.jsdelivr.net/combine/gh/ryersondmp/sa11y@3.0.8/dist/js/lang/en.umd.min.js,gh/ryersondmp/sa11y@3.0.8/dist/js/sa11y.umd.min.js:40:10852
    at Array.forEach (<anonymous>)
    at a (https://cdn.jsdelivr.net/combine/gh/ryersondmp/sa11y@3.0.8/dist/js/lang/en.umd.min.js,gh/ryersondmp/sa11y@3.0.8/dist/js/sa11y.umd.min.js:40:10802)
    at Object.initializeElements (https://cdn.jsdelivr.net/combine/gh/ryersondmp/sa11y@3.0.8/dist/js/lang/en.umd.min.js,gh/ryersondmp/sa11y@3.0.8/dist/js/sa11y.umd.min.js:40:14437)
    at e.Sa11y.checkAll (https://cdn.jsdelivr.net/combine/gh/ryersondmp/sa11y@3.0.8/dist/js/lang/en.umd.min.js,gh/ryersondmp/sa11y@3.0.8/dist/js/sa11y.umd.min.js:40:134506)
    at e (https://cdn.jsdelivr.net/combine/gh/ryersondmp/sa11y@3.0.8/dist/js/lang/en.umd.min.js,gh/ryersondmp/sa11y@3.0.8/dist/js/sa11y.umd.min.js:40:133276)
    at e.Sa11y.initialize (https://cdn.jsdelivr.net/combine/gh/ryersondmp/sa11y@3.0.8/dist/js/lang/en.umd.min.js,gh/ryersondmp/sa11y@3.0.8/dist/js/sa11y.umd.min.js:40:134232)
    at new e.Sa11y (https://cdn.jsdelivr.net/combine/gh/ryersondmp/sa11y@3.0.8/dist/js/lang/en.umd.min.js,gh/ryersondmp/sa11y@3.0.8/dist/js/sa11y.umd.min.js:40:157733)
    at t (https://cdn.jsdelivr.net/gh/ryersondmp/sa11y@latest/bookmarklet/sa11y-en.min.js:7:211)
    at o.onload (https://cdn.jsdelivr.net/gh/ryersondmp/sa11y@latest/bookmarklet/sa11y-en.min.js:7:1036)
```

## URL
`https://yoast.com/duplicate-content/`

**Comment by adamchaboryk** [comment]
Hi @carl-amit, thank you for the bug report! Can you please let me know what browser and operating system you're using? I tried replicating the issue, although the bookmarklet appears to work fine across the Yoast.com website on my end.

If you are using a VPN, please temporarily disable it too. I've had reports of the bookmarklet not working because of VPNs. 

Thanks!

**Comment by adamchaboryk** [comment]
Closing this issue for now. If you experience any issues, please let me know!
