### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by jbrulotte** [ryersondmp/sa11y#92]
## Error Description
```javascript
TypeError: a.trim is not a function
    at https://cdn.jsdelivr.net/combine/gh/ryersondmp/sa11y@3.2.2/dist/js/lang/en.umd.min.js,gh/ryersondmp/sa11y@3.2.2/dist/js/sa11y.umd.min.js:40:153429
    at Array.forEach (<anonymous>)
    at a (https://cdn.jsdelivr.net/combine/gh/ryersondmp/sa11y@3.2.2/dist/js/lang/en.umd.min.js,gh/ryersondmp/sa11y@3.2.2/dist/js/sa11y.umd.min.js:40:153396)
    at https://cdn.jsdelivr.net/combine/gh/ryersondmp/sa11y@3.2.2/dist/js/lang/en.umd.min.js,gh/ryersondmp/sa11y@3.2.2/dist/js/sa11y.umd.min.js:40:153927
    at NodeList.forEach (<anonymous>)
    at https://cdn.jsdelivr.net/combine/gh/ryersondmp/sa11y@3.2.2/dist/js/lang/en.umd.min.js,gh/ryersondmp/sa11y@3.2.2/dist/js/sa11y.umd.min.js:40:153355
    at e.Sa11y.checkAll (https://cdn.jsdelivr.net/combine/gh/ryersondmp/sa11y@3.2.2/dist/js/lang/en.umd.min.js,gh/ryersondmp/sa11y@3.2.2/dist/js/sa11y.umd.min.js:40:155018)
    at https://cdn.jsdelivr.net/combine/gh/ryersondmp/sa11y@3.2.2/dist/js/lang/en.umd.min.js,gh/ryersondmp/sa11y@3.2.2/dist/js/sa11y.umd.min.js:40:142025
```

## URL
`https://www.212performance.com/products/ax360-seamless-knit-cut-resistant-cold-weather-gloves`

**Comment by adamchaboryk** [comment]
Thanks for the bug report @jbrulotte, I'll look into this soon!

**Comment by adamchaboryk** [comment]
Fixed! Thanks again @jbrulotte!
